# Generated by Django 4.1.1 on 2022-10-22 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0007_alter_appointment_description'),
        ('procedure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment_Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment')),
                ('procedureID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedure.procedure')),
            ],
        ),
    ]
