# Generated by Django 4.1.1 on 2022-10-22 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procedure', '0001_initial'),
        ('doctors', '0002_doctor_preferred_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('procedureID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedure.procedure')),
            ],
        ),
    ]
