# Generated by Django 4.0.6 on 2022-08-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointment_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='status',
            new_name='completed',
        ),
        migrations.AddField(
            model_name='appointment',
            name='duration_in_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
