# Generated by Django 4.0.6 on 2022-09-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_rename_status_appointment_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
