const ActionTypes = {
    ADD_APPOINTMENT: 'ADD_APPOINTMENT',
    EDIT_APPOINTMENT: 'EDIT_APPOINTMENT',
    DELETE_APPOINTMENT: 'DELETE_APPOINTMENT',
    SET_APPOINTMENTS: 'SET_APPOINTMENTS',
    ADD_PATIENT: 'ADD_PATIENT',
    EDIT_PATIENT: 'EDIT_PATIENT',
    DELETE_PATIENT: 'DELETE_PATIENT',
    SET_PATIENTS: 'SET_PATIENTS',
    SET_DOCTORS: 'SET_DOCTORS',
    SET_DATA_WAS_FETCHED: 'SET_DATA_WAS_FETCHED',
    SET_APPOINTMENT_CREATE_FORM_VISIBILITY: 'SET_APPOINTMENT_CREATE_FORM_VISIBILITY',
    SET_APPOINTMENT_EDIT_FORM_VISIBILITY: 'SET_APPOINTMENT_EDIT_FORM_VISIBILITY',
    SET_PATIENT_CREATE_FORM_VISIBILITY: 'SET_PATIENT_CREATE_FORM_VISIBILITY',
  };

export default ActionTypes;