# Generated by Django 4.0.6 on 2022-08-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_rename_birtyday_patient_birth_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
