# Generated by Django 4.1.1 on 2022-10-09 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_rename_birth_day_patient_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='middle_name',
        ),
    ]
