# Generated by Django 4.1.1 on 2022-10-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='preferred_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
